# Development Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_dev?currentSchema=ecom
spring.datasource.username=postgres
spring.datasource.password=12345

# JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.com.ksl.template=DEBUG
