spring.application.name=template

################## Undertow Configuration #####################
server.undertow.threads.worker=64
server.undertow.threads.io=8
server.undertow.buffer-size=1024
server.undertow.direct-buffer=true
server.undertow.max-http-post-size=10MB


################## Server Configuration ########################
server.port=10210
server.servlet.context-path=/template

################ Management Configuration #####################
#http://localhost:10215/actuator/health
management.server.port=10215
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health,info,shutdown,configprops,refresh
################ Datasource Configuration ######################
# PostgreSQL datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce?currentSchema=ecom
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true