spring.application.name=template

################## Undertow Configuration #####################
server.undertow.threads.worker=64
server.undertow.threads.io=8
server.undertow.buffer-size=1024
server.undertow.direct-buffer=true
server.undertow.max-http-post-size=10MB


################## Server Configuration ########################
server.port=10210
server.servlet.context-path=/template

################ Management Configuration #####################
#http://localhost:10215/actuator/health
management.server.port=10215
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health,info,shutdown,configprops,refresh